# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0002_auto_20170511_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='street',
            new_name='address',
        ),
    ]
