# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0003_auto_20170519_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='kind',
            field=models.IntegerField(choices=[('Kneipe', 0), ('Bar', 1), ('Club', 2)], default=0),
            preserve_default=False,
        ),
    ]
