# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0004_location_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosnippet',
            name='data',
            field=models.FileField(upload_to='audiosnippets/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
