# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0005_auto_20170628_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='admission',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='beer_price',
            field=models.CharField(max_length=20),
        ),
    ]
