# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0006_auto_20170702_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='kind',
            new_name='type',
        ),
    ]
