# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import stimmungspegel.models


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0007_auto_20170703_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosnippet',
            name='data',
            field=models.FileField(upload_to=stimmungspegel.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='location',
            name='position_lat',
            field=models.DecimalField(blank=True, decimal_places=16, default=0.0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='position_lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19),
        ),
    ]
