# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stimmungspegel', '0009_auto_20170704_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='position_lon',
            field=models.FloatField(blank=True),
        ),
    ]
